name: Set Secrets

on:
  push:
    branches:
      - main

env:
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

jobs:
  set-secrets:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:        
      - name: Display Secrets
        run: echo $GOOGLE_API_KEY